### ISSUE TITLE
Could not build Objective-C module 'Realm'

### ISSUE THREAD

**Issue by daniesy** [FancyPixel/done-swift#1]
![XCode Error](http://s1.postimg.org/vlcczciqn/Screen_Shot_2015_04_05_at_05_34_41.png)

**Comment by andreamazz** [comment]
Hi @Daniesy 
Sometimes the workspace gets out of sync, just select the `Pods-Realm` target (enable it if it's not available) and build it. Once it's built you can switch back to the other targets and they should compile just fine.

**Comment by quantumpotato** [comment]
@andreamazz How do I enable the target? I see it in the Project file but not in my simulator target list.

**Comment by andreamazz** [comment]
Product -> Scheme -> Manage Scheme
Enable the "Show" checkbox for Pods-Realm

**Comment by quantumpotato** [comment]
When I did that, I see "no Scheme". was able to build.. had to restart
Xcode to get my Done target scheme back. Had to fix a few compile errors
then when running I got

_fatal error: unexpectedly found nil while unwrapping an Optional value_

_(lldb)  on_

```
     let directory: NSURL = NSFileManager.defaultManager().
```

containerURLForSecurityApplicationGroupIdentifier("group.it.fancypixel.Done"
)!

do I need to use my own group Identifier?

**Comment by andreamazz** [comment]
Yes, you need your own group id registered in your developer portal for this to work.

**Comment by AliAyasrah** [comment]
@andreamazz 
hello 

same issue here, but I cant find  Pods-Realm 
and if I add realm framework by my self i got pods error 

![Image](http://s2.postimg.org/5rvgucwuh/Screen_Shot_2015_07_16_at_12_26_43.png)

**Comment by andreamazz** [comment]
Checkout the latest commit. I removed the cocoapods integration in favor of the embedded dynamic framework, and updated the syntax to Swift 1.2.
